### ISSUE TITLE
在Ubuntu Server上粘贴时报错

### ISSUE THREAD

**Issue by bwangelme** [lilydjwg/dotzsh#1]
我使用的操作系统是`Ubuntu Server 16.04.2 LTS`，没有安装图形界面，是在Mac上使用Iterm2通过SSH登录上去的。使用的ZSH版本是`zsh 5.1.1 (x86_64-ubuntu-linux-gnu)`。

当我在终端中粘贴东西时，会出现如下的报错：

```
510 (zvv2x) ~/tutorial/vue/guide (master)
>>>                                                                                                                   17:33
_zsh_autosuggest_invoke_original_widget:9: bracketed-paste-url-magic: function definition file not found
510 (zvv2x) ~/tutorial/vue/guide (master)
>>> zsh 5.1.1 (x86_64-ubuntu-linux-gnu)~
```

请教一下，这个`bracketed-paste-url-magic`是干吗的啊，为什么会提示说找不到它？

**Comment by lilydjwg** [comment]
你的 zsh 版本比较旧啦。这个是在粘贴的时候自动转义 URL 里的特殊字符用的，见 https://archive.zhimingwang.org/blog/2015-09-21-zsh-51-and-bracketed-paste.html

我不知道你的 zsh 为什么没有这个文件。它应该位于类似 /usr/share/zsh/functions/Zle/bracketed-paste-url-magic 这样的地方，是 5.1 加入的。

**Comment by bwangelme** [comment]
@lilydjwg 谢谢，已经解决了。

抱歉，一开始没细看，Ubuntu的版本号写错了，是16.04.2，不是16.10。

确实是因为ZSH版本太低导致的问题，我把系统的源从`xenial`切换成了`zesty`(Ubuntu 17.04)，然后装了一个ZSH 5.2-5ubuntu1，换上高版本的ZSH就没问题了。
